spring:
  application:
    name :
      stock-persister-service
  sql:
    init:
      mode: always
  r2dbc:
    url: r2dbc:postgresql://persister-db:5432/webflux
    username: admin
    password: password
  kafka:
    consumer:
      bootstrap-servers: kafka:29092
      group-id: "test-group-2"

api:
  nasdaq:
    kafka:
      trade-topic: "nasdaq-trade"
      order-book-topic: "nasdaq-order-book"
  kospi:
    kafka:
      trade-topic: "kospi-trade"
      order-book-topic: "kospi-order-book"