version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webflux
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:
      context: ./stock-collection-service
      dockerfile: Dockerfile
    container_name: stock-collection-service
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data:
