include:
  - ./kafka/docker-compose.yml

services:
  collection-db:
    image: mysql:8.0
    container_name: stock-collection-service-db
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webflux
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul # 시간대 설정 추가
    volumes:
      - collection-db-data:/var/lib/mysql

  collection-app:
    build:
      context: ./stock-collection-service
      dockerfile: Dockerfile
    container_name: stock-collection-service
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Seoul # 시간대 설정 추가
    depends_on:
        collection-db:
            condition: service_started

  relay-app:
    build:
      context: ./stock-relay-service
      dockerfile: Dockerfile
    container_name: stock-relay-service
    ports:
      - "8090:8080"
    environment:
      TZ: Asia/Seoul # 시간대 설정 추가
    depends_on:
        collection-db:
            condition: service_started

  persister-db:
      image: timescale/timescaledb:latest-pg14
      container_name: stock-persister-service-db
      ports:
        - "25432:5432"
      environment:
        POSTGRES_DB: webflux
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
        TZ: Asia/Seoul # 시간대 설정 추가
      volumes:
        - persister-db-data:/var/lib/postgresql/data

  persister-app:
      build:
        context: ./stock-persister-service
        dockerfile: Dockerfile
      container_name: stock-persister-service
      ports:
        - "8100:8080"
      environment:
        TZ: Asia/Seoul # 시간대 설정 추가
      depends_on:
        persister-db:
          condition: service_started

volumes:
  collection-db-data:
  persister-db-data: