spring:
  application:
    name : stock-collection-service
  sql:
    init:
      mode: always
  r2dbc:
    username : admin
    password : password
    url : r2dbc:mysql://collection-db:3306/webflux?useSSL=false&allowPublicKeyRetrieval=true
  kafka:
    producer:
      bootstrap-servers: kafka:29092

api:
  websocket:
    kospi:
      key-url: "https://openapi.koreainvestment.com:9443/oauth2/Approval"
      websocket-url: "ws://ops.koreainvestment.com:21000/tryitout/"
      trade-id: "H0STASP0"
      order-book-id: "H0STCNT0"
      app-key: "test"
      app-secret: "test"
      trade-topic: "kospi-trade"
      order-book-topic: "kospi-order-book"
    nasdaq:
      key-url: "https://openapi.koreainvestment.com:9443/oauth2/Approval"
      websocket-url: "ws://ops.koreainvestment.com:21000/tryitout/"
      trade-id: "HDFSCNT0"
      order-book-id: "HDFSASP0"
      app-key: "test"
      app-secret: "test"
      trade-topic: "nasdaq-trade"
      order-book-topic: "nasdaq-order-book"

