spring:
  application:
    name : stock-collection-service
  sql:
    init:
      mode: always
  r2dbc:
    username : admin
    password : password
    url : r2dbc:mysql://collection-db:3306/webflux?useSSL=false&allowPublicKeyRetrieval=true
#  kafka:
#    producer:
#      bootstrap-servers: kafka:29092

api:
  websocket:
    kospi-key-url: "https://openapi.koreainvestment.com:9443/oauth2/Approval"
    kospi-trade-url: "ws://ops.koreainvestment.com:21000/tryitout/H0STASP0"
    kospi-order-book-url: "ws://ops.koreainvestment.com:21000/tryitout/H0STCNT0"
    kospi-app-key: "test"
    kospi-app-secret: "test"
