spring:
  application:
    name : stock-collection-service
  r2dbc:
    username : admin
    password : password
    url : r2dbc:mysql://mysql:3306/webflux?useSSL=false&allowPublicKeyRetrieval=true

api:
  websocket:
    kospi-url: "wss://external-api.com/ws/{ticker}"