spring:
  application:
    name : stock-collection-service
  sql:
    init:
      mode: always
  r2dbc:
    username : admin
    password : password
    url : r2dbc:mysql://mysql:3306/webflux?useSSL=false&allowPublicKeyRetrieval=true

api:
  websocket:
    kospi-trade-url: "ws://ops.koreainvestment.com:21000/tryitout/H0STASP0"
    kospi-order-book-url: "ws://ops.koreainvestment.com:21000/tryitout/H0STCNT0"
    kospi-approval_key: "test"